dist: xenial 
sudo: false
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
      - llvm-8-dev
      - llvm-8
      - libllvm-8-ocaml
      - libllvm8
      - llvm-8-runtime

script:
    - export CC=clang-8
    - export CXX=clang++-8
    - mkdir build-asan
    - cd build-asan
    - cmake .. -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
    - cmake --build . -- -j2
    - ctest -j2
    - cd ..
    - mkdir build-tsan
    - cd build-tsan
    - cmake .. -DCMAKE_CXX_FLAGS="-fsanitize=thread -O1"
    - cmake --build . -- -j2
    - ctest -j2


