dist: xenial 
sudo: false
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - clang-7

script:
    - export CC=clang-7
    - export CXX=clang++-7
    - mkdir build-asan
    - cd build-asan
    - cmake .. -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
    - cmake --build . -- -j2
    - ctest -j2
    - cd ..
    - mkdir build-tsan
    - cd build-tsan
    - cmake .. -DCMAKE_CXX_FLAGS="-fsanitize=thread -O1"
    - cmake --build . -- -j2
    - ctest -j2


