name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    if: ${{secrets.ENABLED}} == 'T'

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: marco

      - name: Check run condition
        run: echo "SHOULD_RUN=${{secrets.ENABLED}}" >> $GITHUB_ENV

      - name: Tar
        if: ${{env.SHOULD_RUN}} == 'T'
        run: tar -cvf marco.tar marco

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        if: ${{env.SHOULD_RUN}} == 'T'
        with:
          ssh-private-key: ${{secrets.SSH_KEY}}

      - name: Save server fingerprint
        run: echo "$SSH_FINGERPRINT" > /home/runner/.ssh/known_hosts
        if: ${{env.SHOULD_RUN}} == 'T'
        env:
          SSH_FINGERPRINT: ${{secrets.SERVER_FINGERPRINT}}

      - name: Create temporary directory
        id: create-temp-dir
        if: ${{env.SHOULD_RUN}} == 'T'
        run: echo "TEMP_DIR=$(ssh ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}} mktemp -d)" >> $GITHUB_ENV

      - name: Copy tar to server
        id: copy
        if: ${{env.SHOULD_RUN}} == 'T'
        run: scp marco.tar ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}}:${{env.TEMP_DIR}}/marco.tar

      - name: Untar
        if: ${{env.SHOULD_RUN}} == 'T'
        run: ssh ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}} cd ${{env.TEMP_DIR}} '&&' tar -xvf marco.tar

      - name: Build
        if: ${{env.SHOULD_RUN}} == 'T'
        run: ssh ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}} cd ${{env.TEMP_DIR}} '&&' mkdir marco/build '&&' cd marco/build '&&' cmake .. -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_EXE_LINKER_FLAGS='-fuse-ld=gold' -DBOOST_ROOT=${{secrets.BOOST_ROOT}} -DLLVM_DIR=${{secrets.LLVM_PATH}}/lib/cmake/llvm -DMLIR_DIR=${{secrets.LLVM_PATH}}/lib/cmake/mlir '&&' ninja

      - name: Run tests
        if: ${{env.SHOULD_RUN}} == 'T'
        run: ssh ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}} cd ${{env.TEMP_DIR}} '&&' cd marco/build '&&' ninja test

      - name: Clean remote files
        if: ${{env.SHOULD_RUN}} == 'T' && steps.copy.outcome == 'success'
        run: ssh ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}} rm -r ${{env.TEMP_DIR}}

# Old steps to run tests on Github:
#steps:
#  - uses: actions/checkout@v2
#  - name: fetch libboost
#    run: sudo apt-get install libboost-all-dev
#  - name: fetch llvm key
#    run:  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add
#  - name: add apt repo
#    run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
#  - name: install llvm
#    run: sudo apt install libllvm-11-ocaml-dev libllvm11 llvm-11 llvm-11-dev llvm-11-doc llvm-11-examples llvm-11-runtime clang-11 clang-tools-11 clang-11-doc libclang-common-11-dev libclang-11-dev libclang1-11
#  - name: collect-dependencies
#    run: git submodule update --recursive --init
#  - name: build
#    run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ../ && make all -j4 && make test
