name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch libboost 
      run: sudo apt-get install libboost-all-dev 
    - name: fetch llvm key
      run:  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add
    - name: add apt repo
      run: sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' 
    - name: install llvm
      run: sudo apt-get install libllvm-9-ocaml-dev libllvm9 llvm-9 llvm-9-dev llvm-9-doc llvm-9-examples llvm-9-runtime clang-9 clang-tools-9 clang-9-doc libclang-common-9-dev libclang-9-dev libclang1-9 clang-format-9 python-clang-9 clangd-9 
    - name: collect-dependencies
      run: git submodule update --recursive --init 
    - name: build 
      run: mkdir build && cd build && cmake ../ && make all -j4 && make test

