name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: fetch libboost 
      run: sudo apt-get install libboost-all-dev 
    - name: fetch llvm key
      run:  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add
    - name: add apt repo
      run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main' 
    - name: install llvm
      run: sudo apt install libllvm-11-ocaml-dev libllvm11 llvm-11 llvm-11-dev llvm-11-doc llvm-11-examples llvm-11-runtime clang-11 clang-tools-11 clang-11-doc libclang-common-11-dev libclang-11-dev libclang1-11 
    - name: collect-dependencies
      run: git submodule update --recursive --init 
    - name: build 
      run: mkdir build && cd build && cmake ../ && make all -j4 && make test

